# -*- coding: utf-8 -*-
"""Text Encoder/Decoder V1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18aLpJk21fjShvpBpjJAwY0OZi06xku_3
"""

Text = 'Test Text!'
Key = 'Test Key'

def test():
    alphabet = 'abcdefghijklmnopqrstuvwxyz'
    K = Key
    Key_Index = 0
    x = ''
    for Letter in Text.lower():
        if Key_Index >= len(K):
            Key_Index = 0
        ALPHA = alphabet.find(Letter) + alphabet.find(K[Key_Index])
        ALPH = alphabet.find(K[Key_Index]) + 3
        if Letter.isalpha() == False:
            x += Letter
        else:
            if ALPHA >= 26:
                x += alphabet[ALPHA - 26]
            else:
                x += alphabet[ALPHA]
        if ALPH >= 26:
            K_as_list = list(K)
            K_as_list[Key_Index] = alphabet[ALPH - 26]
            K = ''.join(K_as_list)
        else:
            K_as_list = list(K)
            K_as_list[Key_Index] = alphabet[ALPH]
            K = ''.join(K_as_list)
        Key_Index += 1
    print('Original:', Text)
    print('Different:', x)

test()