# -*- coding: utf-8 -*-
"""Text Encoder/Decoder V3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vpbUCNVQc4tKxm_D9s0CctVpZ9iMGIRF
"""

import string

def main():
  text = input("Message - ")
  key = input("Key - ")
  encode_or_decode = str(input('\nEncode or Decode (e for Encode, d for Decode) - ')).lower()
  symbols = string.ascii_letters + string.digits + string.punctuation
  key_index, changed_text = 0, ''

  for letter in text:
      if key_index == len(key):
          key_index = 0

      key_pos_in_symbols = symbols.find(key[key_index])
      encoded_letter = symbols.find(letter) + (((2 * (encode_or_decode == 'e')) -1) * key_pos_in_symbols)

      if not letter in symbols:
          changed_text += letter
      else:
          changed_text += symbols[encoded_letter - (len(symbols) * (encoded_letter >= len(symbols)))]

      key_index += 1

  if encode_or_decode == 'e':
    print('\n\nOriginal:', text, '\n\nEncrypted:', changed_text)
  else:
    print('\nOriginal:', text, '\nDecoded:', changed_text)

if __name__ == "__main__":
  main()