# -*- coding: utf-8 -*-
"""Text Encoder/Decoder V2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e93X-DlC9cwO_Olr5E5jTKoCCehQtGdy
"""

def Encode_or_Decode_Text():
    alphabet = 'abcdefghijklmnopqrstuvwxyz'
    K = Key
    Key_Index = 0
    x = ''
    for Letter in Text.lower():
        if Key_Index >= len(K):
            Key_Index = 0
        if Encode_or_Decode == 'e':
            ALPHA = alphabet.find(Letter) + alphabet.find(K[Key_Index])
        else:
            ALPHA = alphabet.find(Letter) - alphabet.find(K[Key_Index])
        if Letter.isalpha() == False:
            x += Letter
        else:
            if ALPHA >= 26:
                x += alphabet[ALPHA - 26]
            else:
                x += alphabet[ALPHA]
        Key_Index += 1
    print(f'\nOriginal:', Text)
    print(f'\nDifferent:', x)

Encode_or_Decode = str(input('Encode or Decode (e for Encode, d for Decode) - '))
Text = str(input(f'\nMessage - '))
Key = str(input(f'\nKey - '))
Encode_or_Decode_Text()